name: benchmark
description: Benchmark for Pureflow and other state management libraries.
version: 1.0.0
publish_to: none
resolution: workspace

environment:
  sdk: ^3.5.0

dependencies:
  benchmark_harness: any
  pureflow: any
  signals_core: ^6.2.0
  bloc: ^8.1.3
  bloc_concurrency: ^0.2.3
  riverpod: ^2.4.9
  mobx: ^2.1.1+4
  meta: ^1.14.0
  path: ^1.9.0

dev_dependencies:
  build_runner: any
  mobx_codegen: any

