name: pureflow_workspace
description: Pureflow workspace
version: 0.0.0
publish_to: none

environment:
  sdk: ^3.5.0
  flutter: ">=3.24.0"

dev_dependencies:
  meta: ^1.14.0
  test: any
  pureflow: any

workspace:
- packages/pureflow
- packages/pureflow_flutter
- benchmark
