name: pureflow_workspace
description: Pureflow workspace
version: 0.0.0
publish_to: none

environment:
  sdk: ^3.5.0
  flutter: ">=3.24.0"

dev_dependencies:
  test: any
  benchmark_harness: any
  signals_core: ^6.2.0

  pureflow: any
  meta: any

workspace:
- packages/pureflow
- packages/pureflow_flutter
