name: pureflow_workspace
description: Pureflow workspace
version: 0.0.0
publish_to: none

environment:
  sdk: ^3.5.0

dev_dependencies:
  test: ^1.28.0
  benchmark_harness: ^2.4.0
  signals_core: ^6.2.0

  pureflow: any
  meta: any
workspace:
- packages/pureflow
- packages/pureflow_flutter
