name: pureflow
description: A lightweight, fast, and type-safe reactive state management library for Dart.
version: 1.0.1
repository: https://github.com/arxdeus/pureflow
homepage: https://github.com/arxdeus/pureflow
issue_tracker: https://github.com/arxdeus/pureflow/issues
documentation: https://github.com/arxdeus/pureflow#readme
resolution: workspace

topics:
  - state-management
  - reactive
  - signals
  - pipeline
  - state

environment:
  sdk: ^3.5.0

dependencies:
  meta: ^1.14.0
